# Generated by Django 5.2 on 2025-04-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
