# Generated by Django 5.2 on 2025-04-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='wins',
        ),
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
