# Generated by Django 5.2 on 2025-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pet_breed_remove_pet_wins_pet_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
